//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mainEntities : DbContext
    {
        public mainEntities()
            : base("name=mainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Budget> Budget { get; set; }
        public virtual DbSet<Frequency_> Frequency_ { get; set; }
        public virtual DbSet<Pants> Pants { get; set; }
        public virtual DbSet<Shirt> Shirt { get; set; }
        public virtual DbSet<Shoes> Shoes { get; set; }
        public virtual DbSet<Tie> Tie { get; set; }
    }
}
