//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementApp.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shirt
    {
        public long Id { get; set; }
        public long Brand { get; set; }
        public long Color { get; set; }
        public string Note { get; set; }
    }
}
